### ISSUE TITLE
Hello, I don't find the code about Gaussian Kernel for user inputs in the component LF Module

### ISSUE THREAD

**Issue by sherwin-silin-chen** [ChungYi347/Interactive-Multi-Class-Tiny-Object-Detection#2]
As the title says, I don't see your code about Gaussian Kernel. When I read your paper, I don't know how to produce the heatmap by max operation. Could you tell me something about it? Thanks a lot!

**Comment by ChungYi347** [comment]
Hello~
The code of drawing gaussian kernel by using user inputs is [here.](https://github.com/ChungYi347/Interactive-Multi-Class-Tiny-Object-Detection/blob/master/mmdet/datasets/drawer/userinput.py#L106)
Our drawer code makes the gaussian kernel.
I will specify that which part I changed compared to original code in the future, then it would be beneficial for other readers.
Thank you for your interest in our work.

**Comment by sherwin-silin-chen** [comment]
> Hello~
> The code of drawing gaussian kernel by using user inputs is [here.](https://github.com/ChungYi347/Interactive-Multi-Class-Tiny-Object-Detection/blob/master/mmdet/datasets/drawer/userinput.py#L106)
> Our drawer code makes the gaussian kernel.
> I will specify that which part I changed compared to original code in the future, then it would be beneficial for other readers.
> Thank you for your interest in our work.

Thanks again for your reply. I'll learn the code.
