### ISSUE TITLE
ImportError: cannot import name 'deform_conv_cuda' from 'mmdet.ops.dcn'  (/data/ykb/Interactive-Multi-Class-Tiny-Object-Detection-master/tools/../mmdet/ops/dcn/__init__.py)

### ISSUE THREAD

**Issue by Brynn-bing** [ChungYi347/Interactive-Multi-Class-Tiny-Object-Detection#4]
Hi,
I am getting an error on running the following lines on DOTA2_tiny dataset.
python ./tools/train.py ./configs/DOTA2_Tiny/faster_rcnn_obb_r50_fpn_1x_dota2_tiny.py

Error :
ImportError: cannot import name 'deform_conv_cuda' from 'mmdet.ops.dcn' (/data/ykb/Interactive-Multi-Class-Tiny-Object-Detection-master/tools/../mmdet/ops/dcn/__init__.py)

I am using :
python : 3.7.12
pytorch : 1.4.0
cuda : 9.2
cudnn: 7.6.5
mmcv : 0.4.3
mmdet: 0.6.0+unknown
gcc : 5.4.0

I guess I followed the instructions based on the Github repository. 
I hope to get your solution to this problem，and could you tell me of the environment you are using.
thanks.

**Comment by ChungYi347** [comment]
Hi~
Did you follow 3rd installation instructions?

3. Install external libraries (e.g., mmdet and mmcv) with:
```
bash install.sh
```

The error usually occurs when the installation is not properly installed as I mentioned above or the version does not match.

Version:
python: 3.7.13
pytorch: 1.4.0
cuda: 9.2
cudnn: 7.6.5
mmcv: 0.4.3
mmdet: 2.2.0+36d7fc8

We used similar versions, so I think it is related to install.sh script.
Could you install the install.sh script and please leave a comment?

**Comment by Brynn-bing** [comment]
Hi,

I'm sorry to reply so late, Thank you very much for your reply and guidance. 

The error occurred because the compile.sh file did not run successfully. After running the file successfully, the problem is resolved.

Thanks again for your reply.
